name: Easy WireGuard Connection
description: Easy WireGuard Connection Setup

inputs:
  WG_CONFIG:
    description: WireGuard (wg-quick) configuration file
    required: true

runs:
    using: composite
    steps:
        - run: |
              echo "update system"
              sudo apt update -y
              echo "install resolvconf and wireguard"
              sudo apt install -y resolvconf
              sudo apt install -y wireguard
              sudo apt install -y wireguard-tools
              sudo apt install -y net-tools
              sudo apt install -y iptables
              sudo apt install -y iproute2
              echo "add sysctl variables"
              sudo sysctl -w net.ipv4.ip_forward=1
              sudo sysctl -w net.ipv4.conf.all.src_valid_mark=1
              sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
              sudo sysctl -w net.ipv6.conf.all.forwarding=1
              sudo sysctl -w net.ipv6.conf.default.forwarding=1
              echo "net.ipv4.ip_forward=1" | sudo tee /etc/sysctl.conf
              echo "net.ipv4.conf.all.src_valid_mark=1" | sudo tee /etc/sysctl.conf
              echo "ipv6.conf.all.disable_ipv6=1" | sudo tee /etc/sysctl.conf
              echo "net.ipv6.conf.all.forwarding=1" | sudo tee /etc/sysctl.conf
              echo "net.ipv6.conf.default.forwarding=1" | sudo tee /etc/sysctl.conf
              echo "load sysctl variables"
              sudo sysctl -p /etc/sysctl.conf
              echo "write wireguard config"
              sudo mkdir -p /etc/wireguard
              echo "${{ inputs.WG_CONFIG }}" > /etc/wireguard/wg0.conf
              sudo cat /etc/wireguard/wg0.conf
              echo "set permissions"
              sudo chmod 600 /etc/wireguard/wg0.conf
              echo "setting config"
              sudo wg-quick up /etc/wireguard/wg0.conf
              sleep 5
              sudo wg show
              sudo wg showconf wg0
              sudo ifconfig
              sudo ip a
              sudo ip r
          shell: bash

